#!/bin/bash

# Interpret the instructions
function interpret
{
  instructions=$*
  # Comments are skipped
  if [[ $instructions == "👃"* ]]; then continue
  # Log mixed data to file
  elif [[ $instructions == "🚽"* ]]; then eval "echo ${instructions/🚽}" >> "🚽.log"
  # Evaluate statements
  elif [[ $instructions == "💩"* ]]; then eval "${instructions/💩}"
  # Output text to stdout
  elif [[ $instructions ]]; then eval "echo $instructions"
  fi
}

# Read from user input
function interactive_mode
{
  while read -p "🚻 " line; do
    interpret $line
  done
}

# Read from file
function batch_mode
{
  while read -r line; do
    interpret $line
  done < "$1"
}

case "$1" in
  -i|--interactive)
    interactive_mode
    exit 0
    ;;
  *)
    batch_mode $*
    exit 0
    ;;
esac
